version: '3'
services:
  docker-app:
    image: viniciusll/locadora-api
    ports:
      - "8080:8080"
    depends_on:
      - docker-postgres
  docker-postgres:
    image: postgres:10.4
    environment:
      - POSTGRES_DB=locadora
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456